name: "Get Content Action"
description: "Get content from a branch"

inputs:
  branch:
    description: "Branch name"
    required: false
    default: "main"
  path:
    description: "Path to the file"
    required: true

outputs:
  content:
    value: ${{ steps.get-content.outputs.result }}
    description: "Content from the branch"

runs:
  using: "composite"
  steps:
    - run: |
        gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/odan-sandbox/cli-release-flow-sandbox/contents/${{ inputs.path }}?ref=${{ inputs.branch }} \
        --jq '.content' | base64 -d | tr -d '\n' >> VERSION
        echo "result=${cat VERSION}" >> "$GITHUB_OUTPUT"
      id: get-content
      shell: bash
