name: Check Release
on:
  pull_request:
    branches:
      - release/cli

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-content
        id: main-version
        with:
          path: VERSION
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: ./.github/actions/get-content
        id: release-version
        with:
          branch: release/cli
          path: VERSION
        env:
          GH_TOKEN: ${{ github.token }}

      - run: |
          echo "Version: ${{ steps.main-version.outputs.content }}"

      - run: |
          echo "Version of release branch: ${{ steps.release-version.outputs.content }}"
