name: Check Release
on:
  pull_request:
    branches:
      - release/cli
    types:
      - labeled
      - unlabeled
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        with:
          label_prefix: "bump:"

      - uses: LouisBrunner/checks-action@v2.0.0
        if: ${{ steps.release-label.outputs.level == null }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: neutral
