name: Check Release
on:
  pull_request:
    branches:
      - release/cli
    types:
      - labeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        with:
          label_prefix: "bump:"

      - run: exit 1
        if: ${{ steps.release-label.outputs.level == null }}
