name: Create Release Pull Request
on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ODAN_SANDBOX_BOT_APP_ID }}
          private-key: ${{ secrets.ODAN_SANDBOX_BOT_PRIVATE_KEY }}

      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release/cli
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
