name: Release

on:
  push:
    branches:
      - release/cli

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get a number of pull request
        id: get-pr-number
        run: |
          PR_NUMBER=$(gh pr list --base release/cli --state merged --limit 1 --json number --jq '.[].number')
          echo "result=${PR_NUMBER}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get labels of the pull request
        id: get-labels
        run: |
          LABELS=$(gh pr view ${{ steps.get-pr-number.outputs.result }} --json "labels" --jq '[.labels[] | .name]')
          echo "result=${LABELS}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        with:
          labels: ${{ fromJSON(steps.get-labels.outputs.result) }}
          label_prefix: "bump:"

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
